<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-U01S286" ignored="0" name="Test" tests="5" failures="1" timestamp="2022-02-26T13:18:47 IST" time="14.413" errors="0">
  <testcase name="login" time="14.316" classname="com.TestNG.IretryAnalayzer_Concept"/>
  <testcase name="login2" time="0.01" classname="com.TestNG.IretryAnalayzer_Concept">
    <skipped/>
  </testcase> <!-- login2 -->
  <testcase name="login2" time="0.003" classname="com.TestNG.IretryAnalayzer_Concept">
    <skipped/>
  </testcase> <!-- login2 -->
  <testcase name="login2" time="0.003" classname="com.TestNG.IretryAnalayzer_Concept">
    <skipped/>
  </testcase> <!-- login2 -->
  <testcase name="login2" time="0.002" classname="com.TestNG.IretryAnalayzer_Concept">
    <failure type="java.lang.AssertionError" message="expected [revathi1] but found [revathi]">
      <![CDATA[java.lang.AssertionError: expected [revathi1] but found [revathi]
at com.TestNG.IretryAnalayzer_Concept.login2(IretryAnalayzer_Concept.java:41)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- login2 -->
</testsuite> <!-- Test -->
